<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.BetterJellyfinSearch</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.BetterJellyfinSearch</AssemblyName>
    <Version>1.0.1.0</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.3">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.11.3">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <None Remove="Assets\better-jellyfin-search.css" />
    <None Remove="Assets\better-jellyfin-search.js" />
    <None Remove="Assets\bootstrap.js" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Assets\better-jellyfin-search.css" />
    <EmbeddedResource Include="Assets\better-jellyfin-search.js" />
    <EmbeddedResource Include="Assets\bootstrap.js" />
  </ItemGroup>
</Project>
